In [1]:
import numpy as np

## ベクトルと行列

In [2]:
x = np.array([1, 2, 3])
print(x.__class__)
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [3]:
W = np.array([[1, 2, 3,], [4, 5, 6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


## 行列の要素ごとの演算

In [5]:
W = np.array([[1, 2, 3,], [4, 5, 6,]])
X = np.array([[0, 1, 2,], [3, 4, 5,]])

print(W + X)
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


## ブロードキャスト

In [6]:
A = np.array([[1, 2,], [3, 4]])
print(A * 3)

[[ 3  6]
 [ 9 12]]


In [7]:
A = np.array([[1, 2,], [3, 4,]])
b = np.array([10, 20])
print(A * b)

[[10 40]
 [30 80]]


## ベクトルの内積と行列の積

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [9]:
A = np.array([[1, 2,], [3, 4,]])
B = np.array([[5, 6,], [7, 8,]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [10]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
print(h)


[[ 0.49862223  0.80737152  1.5466629   0.02607197]
 [ 0.58070027  0.8551781  -0.4493182  -1.52873169]
 [-1.79289764 -1.22629194  1.08980994 -2.57356028]
 [ 0.92001565  1.16977274  0.70033481 -0.25773441]
 [ 0.85831987  1.11684141  0.83449052 -0.20779237]
 [-1.99135603 -1.4131451   0.18804627 -3.50476027]
 [-0.39621358  0.00428491  0.64939312 -1.57776646]
 [-2.51344481 -1.85714436  1.63856289 -2.82397619]
 [-0.73185036 -0.27973087  1.69597869 -1.04668193]
 [-1.70442285 -1.16033337  0.0978437  -3.29995938]]
