In [1]:
import numpy as np

## ベクトルと行列

In [2]:
x = np.array([1, 2, 3])
print(x.__class__)
print(x.shape)
print(x.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [3]:
W = np.array([[1, 2, 3,], [4, 5, 6]])
print(W.shape)
print(W.ndim)

(2, 3)
2


## 行列の要素ごとの演算

In [4]:
W = np.array([[1, 2, 3,], [4, 5, 6,]])
X = np.array([[0, 1, 2,], [3, 4, 5,]])

print(W + X)
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


## ブロードキャスト

In [5]:
A = np.array([[1, 2,], [3, 4]])
print(A * 3)

[[ 3  6]
 [ 9 12]]


In [6]:
A = np.array([[1, 2,], [3, 4,]])
b = np.array([10, 20])
print(A * b)

[[10 40]
 [30 80]]


## ベクトルの内積と行列の積

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [8]:
A = np.array([[1, 2,], [3, 4,]])
B = np.array([[5, 6,], [7, 8,]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [10]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
print(h)


[[-0.7643658  -0.21055573 -0.48540319  2.03584999]
 [ 3.33746739 -1.95299487  1.37184783  1.70247058]
 [-1.3894654   1.05249362 -0.6219204   1.8163495 ]
 [ 1.85236299 -2.27734326  0.55910774  2.0820179 ]
 [ 1.9348095  -1.88851457  0.65869561  1.96046143]
 [ 1.45504783  0.36797619  0.74297509  1.44321508]
 [-2.04594329  0.18018407 -1.08825452  2.18165221]
 [-0.11355597 -0.42294761 -0.18131511  1.96559349]
 [-1.18263903 -0.21438242 -0.7014519   2.11903037]
 [ 1.39384651 -2.0992048   0.34905433  2.1237925 ]]


In [11]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [12]:
a = sigmoid(h)
a

array([[0.31769916, 0.44755468, 0.38097706, 0.88451001],
       [0.96569203, 0.12422717, 0.79767853, 0.84585713],
       [0.19949312, 0.74125346, 0.34934481, 0.86012752],
       [0.86440431, 0.09301685, 0.63624606, 0.88914309],
       [0.8737808 , 0.13141393, 0.65896732, 0.87658288],
       [0.81077408, 0.59096987, 0.67764608, 0.80895203],
       [0.11446293, 0.54492454, 0.25194711, 0.89858973],
       [0.47164147, 0.39581163, 0.454795  , 0.87713702],
       [0.23457802, 0.44660873, 0.3314904 , 0.89273912],
       [0.80120561, 0.10917413, 0.58638824, 0.89319427]])

In [15]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2
print(s)

[[ 1.5139806  -0.30518016 -2.43430096]
 [ 0.64250845 -0.78898062 -1.94363282]
 [ 1.63798663 -0.26034762 -2.41880324]
 [ 0.58812129 -0.74040569 -2.11378545]
 [ 1.95280932 -0.09176985 -2.43300401]
 [ 0.95172251 -0.48175151 -2.27594623]
 [ 1.13107675 -0.4380497  -2.14982999]
 [ 0.52269061 -0.61898075 -2.51412039]
 [ 1.36795745 -0.40561196 -2.46825765]
 [ 1.63222973 -0.2544772  -2.47087955]]
